include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_use_package_imports: true
    avoid_print: true
    prefer_final_locals: true
    unnecessary_this: true
    prefer_single_quotes: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    control_flow_in_finally: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
